# Generated by Django 6.0.3 on 2026-04-11 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('headline', models.CharField(blank=True, help_text="Short title, e.g. 'Backend Developer'", max_length=200)),
                ('location', models.CharField(blank=True, help_text='City / Country', max_length=200)),
                ('bio', models.TextField(blank=True, help_text="Short 'About me' paragraph.")),
                ('years_of_experience', models.PositiveIntegerField(blank=True, help_text='Total years of professional experience.', null=True)),
                ('current_role', models.CharField(blank=True, help_text='Your current role / company.', max_length=200)),
                ('website_url', models.URLField(blank=True, help_text='Personal website or portfolio URL.')),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL.')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL.')),
                ('primary_tech_stack', models.CharField(blank=True, help_text="Primary tech stack, e.g. 'Python, Django, DRF, PostgreSQL'.", max_length=300)),
                ('spoken_languages', models.CharField(blank=True, help_text="Spoken languages, e.g. 'English, French'.", max_length=200)),
                ('availability', models.CharField(blank=True, help_text="Availability, e.g. 'Open to work', 'Full-time only', 'Freelance'.", max_length=200)),
                ('education_summary', models.TextField(blank=True, help_text='Short education summary (not full list).')),
                ('profile_picture_url', models.URLField(blank=True, help_text='URL to a profile picture/avatar.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
