# Generated by Django 6.0.3 on 2026-04-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developerprofile',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture/avatar.', null=True, upload_to='profile_pics/'),
        ),
    ]
