# Generated by Django 6.0.3 on 2026-04-12 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_category_description_alter_category_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCheckerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('checker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='curriculum.checker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checker_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User checker progress',
                'verbose_name_plural': 'User checker progress',
                'unique_together': {('user', 'checker')},
            },
        ),
    ]
